apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/sales/
patches:
- path: ./dev-sales-deploy.yaml
- path: ./dev-sales-service.yaml
images:
- name: service-image
  newName: ardanlabs/service/sales-api
  newTag: 0.0.1
